all:
  children:
    dns:
      hosts:
        ns.contoso.local:
          ansible_host: 34.85.113.128
          ansible_ssh_private_key_file: ~/gcp
          ansible_user: y14a
    master:
      hosts:
        master-01.contoso.local:
          ansible_host: 127.0.0.1
          ansible_ssh_private_key_file: ~/gcp
          ansible_user: ansible
        master-02.contoso.local:
          ansible_host: 127.0.0.1
          ansible_ssh_private_key_file: ~/gcp
          ansible_user: ansible
    worker:
      hosts:
        worker-01.contoso.local:
          ansible_host: 127.0.0.1
          ansible_ssh_private_key_file: ~/gcp
          ansible_user: ansible
